# Generated by Django 5.1.4 on 2025-01-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_userpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='time',
        ),
        migrations.AddField(
            model_name='userpost',
            name='timen',
            field=models.TimeField(auto_now=True),
        ),
    ]
