# Generated by Django 5.1.4 on 2025-01-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_userpost_time_userpost_timen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='timen',
            new_name='time',
        ),
    ]
