# Generated by Django 5.1.4 on 2025-01-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_timen_userpost_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
